bleach-allowed=允许漂白 (通常指可使用任何漂白剂)
bleach-dont=不可漂白
bleach-oxygen=允许氧漂 / 可使用氧系漂白剂 (非氯漂) 
drying-drip=滴干
drying-drip-shade=阴凉处滴干
drying-flat=平铺晾干 
drying-flat-drip=平铺滴干
drying-flat-drip-shade=阴凉处平铺滴干
drying-flat-shade=阴凉处平铺晾干
drying-line=悬挂晾干 
drying-line-alt=悬挂晾干 (另一种符号表示)
drying-line-drip=悬挂滴干 
drying-line-drip-shade=阴凉处悬挂滴干
drying-line-shade=阴凉处悬挂晾干 
drying-line-shade-alt=阴凉处悬挂晾干
iron-dont=不可熨烫
iron-high=可高温熨烫 (最高200℃)
iron-low=可低温熨烫 (最高110℃)
iron-medium=可中温熨烫 (最高150℃)
machine-wash=可机洗
machine-wash-permanent-press=可机洗 / 免烫洗 (通常指合成纤维或抗皱处理的衣物)
wash-30=最高洗涤温度30℃ (常规过程)
wash-40=最高洗涤温度40℃
wash-50=最高洗涤温度50℃
wash-60=最高洗涤温度60℃
wash-70=最高洗涤温度70℃
wash-90=最高洗涤温度90℃
wash-95=最高洗涤温度95℃
wash-cotton-30=棉织物 / 棉洗程序，最高洗涤温度30℃
wash-cotton-40=棉织物程序，最高40℃
wash-cotton-60=棉织物程序，最高60℃
wash-cotton-95=棉织物程序，最高95℃
wash-delicate-30=精细织物 / 轻柔洗程序，最高30℃
wash-delicate-40=精细织物程序，最高40℃
wash-dont=不可水洗
wash-easycare-30=易护理 / 免烫程序，最高30℃
wash-easycare-40=易护理程序，最高40℃
wash-easycare-60=易护理程序，最高60℃
wash-gentle-30=温和洗涤程序，最高30℃
wash-gentle-40=温和洗涤程序，最高40℃
wash-hand=仅可手洗
wash-mild-30=缓和洗涤程序，最高30℃
wash-mild-40=缓和洗涤程序，最高40℃
wash-mild-60=缓和洗涤程序，最高60℃
professional-dry-dont=不可干洗
professional-dry-f=使用碳氢化合物溶剂（蒸馏温度150℃-210℃，闪点38℃-70℃）的专业干洗（常规干洗）
professional-dry-f-mild=使用碳氢化合物溶剂的专业干洗（缓和干洗）
professional-dry-p=使用四氯乙烯和碳氢化合物溶剂的专业干洗（常规干洗）
professional-dry-p-gentle=使用四氯乙烯和碳氢化合物溶剂的专业干洗（温和干洗）
professional-dry-p-mild=使用四氯乙烯和碳氢化合物溶剂的专业干洗（缓和干洗）
professional-dry-w=专业湿洗 (常规湿洗)
professional-wet=专业湿洗
professional-wet-dont=不可专业湿洗
professional-wet-mild=专业湿洗 (缓和湿洗)
professional-wet-very-mild=专业湿洗 (非常缓和湿洗)
professional-wet-w-dont=不可专业湿洗
professional-wet-w-gentle=专业湿洗 (温和湿洗)
professional-wet-w-mild=专业湿洗 (缓和湿洗)
tumble-dry-dont=不可转笼烘干
tumble-dry-low=可使用转笼烘干，低温
tumble-dry-medium=可使用转笼烘干，中温